### ISSUE TITLE
Remove name property from authorize API metadata

### ISSUE THREAD

**Issue by rufuspollock** [datahq/bitstore#1]
Currently have:

```
{
    "metadata": {
        "owner": "<user-id-of-uploader>",
        "name": "<data-set-unique-id>"
    },
    "filedata": {
        "<relative-path-to-file-in-package-1>": {
            "length": 1234, #length in bytes of data
```

However, not sure we need name property in metadata?

/cc @akariv

**Comment by akariv** [comment]
If provided, it could be used for formatting the upload path. 
Let's keep it as an optional argument.

**Comment by rufuspollock** [comment]
@akariv i agree on keeping as optional. I think i might rename to `dataset` consistent with source API.

**Comment by rufuspollock** [comment]
@zelima when you do do this notify me as it will need a change in CLI.

**Comment by zelima** [comment]
@rufuspollock check the PR https://github.com/datahq/bitstore/pull/12. this should fix

**Comment by zelima** [comment]
FIXED
