### ISSUE TITLE
Change storage upload url to always be md5 hash page

### ISSUE THREAD

**Issue by rufuspollock** [datahq/bitstore#2]
The idea of the rawstore is that the user MUST upload to storage object store at path that is md5 of the file.

Note: this may not be true for all deployments of this bitstore e.g. if we used it for the package store it would be different.

We could leave it to the client to be well-behaved and have already created an upload path that includes the md5 (but that seems dubious).

However, for now making sure we return an upload url that is the md5 hash makes sense and we can refactor later if / when we have the need.

**Comment by akariv** [comment]
Perhaps we should have it as a configuration parameter - e.g. as an env var containing a format string, such as
`/files/{md5}/{filename}`

**Comment by rufuspollock** [comment]
@akariv agreed. I think the spec is that an env var parameter:

```
PATH with 

e.g.

/files/{md5}
/{md5}
/files/
```

PATH may contain any format string available for a file in authorize API including {path} which is full path string (relative path to file in package). If the format variable is not available throw an error reporting that.

```
{
  "metadata": {
        "owner": "<user-id-of-uploader>",
        "name": "<data-set-unique-id>"
    },
  "filedata": {
      "<relative-path-to-file-in-package-1>": {
          "length": 1234, // or size?
          "md5": "<md5-hash-of-the-data>",
          "type": "<content-type-of-the-data>",
          "name": "<file-name>"
      },
      "<relative-path-to-file-in-package-2>": {
          "length": 4321,
          "md5": "<md5-hash-of-the-data>",
          "type": "<content-type-of-the-data>",
          "name": "<file-name>"
      }
      ...
  }
}
``` 

@zelima can you look into this.

**Comment by zelima** [comment]
FXIED
