### ISSUE TITLE
Cannot get datapackage.json using revision id

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/bitstore#22]
E.g., the latest successful revision for `core/finance-vix` is 35 (http://api-testing.datahub.io/source/core/finance-vix/successful)

But if I try to get datapackage.json for revision 35, I get 404 - https://pkgstore-testing.datahub.io/core/finance-vix/35/datapackage.json

However, using old "latest" prefix still works - https://pkgstore-testing.datahub.io/core/finance-vix/latest/datapackage.json

**Comment by zelima** [comment]
FIXED for quite long time already. At this point latest revision is 209 and it's working for both

* https://pkgstore.datahub.io/core/finance-vix/209/datapackage.json
* https://pkgstore.datahub.io/core/finance-vix/latest/datapackage.json
