### ISSUE TITLE
Reinstate proper permission checking

### ISSUE THREAD

**Issue by rufuspollock** [datahq/bitstore#8]
See TODO: here https://github.com/datahq/bitstore/commit/e47a62937b580683baa3f2d383b607066489b6f0?diff=unified#diff-ef6c11d0e1f2862e56b50cae69053172R30

Also need to re-add SERVICE_NAME to allow for multiple deployments of this app as different services (e.g. rawstore and pkgstore).

**Comment by zelima** [comment]
FIXED/OBSOLETE services are checked here https://github.com/datahq/auth/blob/master/auth/permissions.py#L13 and permissions assigned appropriately
